import React, { useEffect, useMemo, useState } from "react";
import { FaCalendarAlt, FaPlus, FaSearch, FaTag } from "react-icons/fa";
import config from "../config";

export default function CouponManager() {
  const [coupons, setCoupons] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [query, setQuery] = useState(""); const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ code: "", discountType: "percent", discountValue: "", expiryDate: "" });
  const fetchCoupons = async () => { setLoading(true); try { const response = await fetch(`${config.apiUrl}/api/coupons`); if (!response.ok) throw new Error("Unable to load promotions."); setCoupons(await response.json()); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { fetchCoupons(); }, []);
  const filtered = useMemo(() => coupons.filter((coupon) => coupon.code.toLowerCase().includes(query.toLowerCase())), [coupons, query]);
  const createCoupon = async (event) => { event.preventDefault(); setError(""); setNotice(""); try { const response = await fetch(`${config.apiUrl}/api/coupons`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, discountValue: Number(form.discountValue), expiryDate: form.expiryDate || undefined }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to create promotion."); setCoupons((current) => [data.coupon, ...current]); setForm({ code: "", discountType: "percent", discountValue: "", expiryDate: "" }); setShowForm(false); setNotice(`Promotion ${data.coupon.code} is ready to use.`); } catch (err) { setError(err.message); } };
  const activeCount = coupons.filter((coupon) => coupon.isActive && (!coupon.expiryDate || new Date(coupon.expiryDate) >= new Date())).length;
  return <div className="max-w-[1440px] mx-auto space-y-6"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="text-sm text-slate-500">Pricing and offers</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Promotions</h1><p className="mt-1 text-sm text-slate-500">Create customer coupon codes for checkout discounts.</p></div><button onClick={() => setShowForm((value) => !value)} className="self-start inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2.5 rounded-lg text-sm font-semibold shadow-sm"><FaPlus size={12} /> New promotion</button></div>
    <div className="grid sm:grid-cols-2 gap-4"><div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">Active promotions</p><p className="mt-2 text-2xl font-bold text-slate-900">{activeCount}</p><p className="mt-1 text-xs text-slate-500">Available at checkout</p></div><div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">Total codes</p><p className="mt-2 text-2xl font-bold text-slate-900">{coupons.length}</p><p className="mt-1 text-xs text-slate-500">Created by your store</p></div></div>
    {showForm && <form onSubmit={createCoupon} className="bg-white border border-slate-200 rounded-xl p-5 md:p-6 shadow-sm"><div className="flex justify-between gap-4"><div><h2 className="font-bold text-slate-900">Create promotion</h2><p className="mt-1 text-sm text-slate-500">It will be available to cashiers as soon as it is saved.</p></div><button type="button" onClick={() => setShowForm(false)} className="text-sm text-slate-500 hover:text-slate-800">Cancel</button></div><div className="grid md:grid-cols-4 gap-4 mt-5"><label className="text-sm font-medium text-slate-700">Code<input required value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} placeholder="SAVE10" className="mt-1.5 w-full border border-slate-200 rounded-lg px-3 py-2.5 uppercase text-sm" /></label><label className="text-sm font-medium text-slate-700">Discount type<select value={form.discountType} onChange={(e) => setForm({ ...form, discountType: e.target.value })} className="mt-1.5 w-full border border-slate-200 rounded-lg px-3 py-2.5 text-sm bg-white"><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label><label className="text-sm font-medium text-slate-700">Value<input required min="0" step="0.01" type="number" value={form.discountValue} onChange={(e) => setForm({ ...form, discountValue: e.target.value })} placeholder={form.discountType === "percent" ? "10" : "100"} className="mt-1.5 w-full border border-slate-200 rounded-lg px-3 py-2.5 text-sm" /></label><label className="text-sm font-medium text-slate-700">Expiry date <span className="text-slate-400 font-normal">(optional)</span><input type="date" value={form.expiryDate} onChange={(e) => setForm({ ...form, expiryDate: e.target.value })} className="mt-1.5 w-full border border-slate-200 rounded-lg px-3 py-2.5 text-sm" /></label></div><button className="mt-5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg px-4 py-2.5 text-sm font-semibold">Save promotion</button></form>}
    {notice && <div className="bg-emerald-50 border border-emerald-200 text-emerald-800 rounded-lg px-4 py-3 text-sm">{notice}</div>}{error && <div className="bg-rose-50 border border-rose-200 text-rose-700 rounded-lg px-4 py-3 text-sm">{error}</div>}
    <section className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden"><div className="p-5 border-b border-slate-100 flex flex-col sm:flex-row justify-between gap-3"><div><h2 className="font-bold text-slate-900">Promotion codes</h2><p className="mt-1 text-sm text-slate-500">Codes currently saved in the checkout system.</p></div><div className="relative"><FaSearch className="absolute left-3 top-3 text-slate-400 text-xs" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search codes" className="border border-slate-200 rounded-lg pl-8 pr-3 py-2 text-sm" /></div></div>{loading ? <div className="p-12 text-center text-sm text-slate-500">Loading promotions…</div> : filtered.length === 0 ? <div className="p-12 text-center"><FaTag className="mx-auto text-3xl text-slate-200" /><p className="mt-3 font-medium text-slate-700">No promotion codes yet</p><p className="mt-1 text-sm text-slate-500">Create a code to offer a checkout discount.</p></div> : <div className="divide-y divide-slate-100">{filtered.map((coupon) => { const expired = coupon.expiryDate && new Date(coupon.expiryDate) < new Date(); return <div key={coupon._id} className="p-5 flex flex-col sm:flex-row sm:items-center gap-4"><div className="w-10 h-10 shrink-0 grid place-items-center rounded-lg bg-emerald-50 text-emerald-600"><FaTag /></div><div className="flex-1"><p className="font-bold text-slate-900 tracking-wide">{coupon.code}</p><p className="mt-1 text-sm text-slate-500">{coupon.discountType === "percent" ? `${coupon.discountValue}% off` : `₱${coupon.discountValue} off`}</p></div><div className="flex items-center gap-3"><span className="inline-flex items-center gap-1 text-xs text-slate-500"><FaCalendarAlt size={11} />{coupon.expiryDate ? new Date(coupon.expiryDate).toLocaleDateString("en-PH", { dateStyle: "medium" }) : "No expiry"}</span><span className={`px-2.5 py-1 rounded-full text-xs font-semibold ${coupon.isActive && !expired ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{expired ? "Expired" : coupon.isActive ? "Active" : "Inactive"}</span></div></div>; })}</div>}</section>
  </div>;
}
